config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  
  resources :users, only: [:index, :show, :edit, :update] do
     resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings',as: 'followings'
    get 'followers' => 'relationships#followers',as: 'followers'
  end
  resources :books, only: [:index, :show, :edit, :create, :destroy, :update] do
      resource :favorites, only: [:create, :destroy]
      resources :book_comments, only: [:create, :destroy]
    end

  root 'homes#top'
  get '/home/about' => 'homes#about'
  get "search" => "search#search"
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  before_action :authenticate_user!
  
  
  def create
      @book = Book.find(params[:book_id])
      @book_comment =BookComment.new(book_comment_params)
      @book_comment.book_id = @book.id
      @book_comment.user_id = current_user.id
      if @book_comment.save
         redirect_to book_path(@book.id)
      else      
         render 'books/show' 
      end     
  end

  def destroy
      @book = Book.find(params[:book_id])
      book_comment =@book.book_comments.find(params[:id])
      book_comment.destroy
    #   redirect_to request.referer
  end
  
  private
  def book_comment_params
      params.require(:book_comment).permit(:comment)
  end
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_comment_form.html.erb
<%= form_with(model:[book, @book_comment], id: "new_comment") do |f| %> <!--配列でインスタンス変数を2つ指定。コメントは、@bookに結びついた@commentだから-->
  <%= f.text_area :comment, size: "10x10", class: "form-control" %> <br>
  
  <%= f.submit "送信"  %>
<% end %>

app/views/book_comments/_comment_index.html.erb
<!--コメント一覧の部分テンプレート-->
  
<tbody>
  <% book.book_comments.each do |book_comment| %>
     <tr>
       <th><%= attachment_image_tag(book_comment.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></th>
       <th><%= link_to @book.user.name,books_path %></th>
        
        <th><%= book_comment.comment %></th>
        <th>
       
          <%= link_to "Destroy", book_book_comment_path(book,book_comment), method: :delete, remote: true, class: "btn-sm btn-danger" %>

        </th>
      
    </tr>
  <% end %>
</tbody>

app/views/book_comments/create.js.erb
<!--エスケープされていないと実行される可能性がある悪意のあるコード（悪意のあるユーザー）を投稿する可能性があります。-->
$('#comment_area').html("<%= escape_javascript(render 'book_comments/comment_index', book: @book) %>");
$('#comment_form').html("<%= escape_javascript(render "book_comments/comment_form", book: @book, comment: @comment_new) %>");

$("textarea").val('') <!--#発火した際のtext_fieldを空白に更新するように指定-->

app/views/book_comments/destroy.js.erb
<!--エスケープされていないと実行される可能性がある悪意のあるコード（悪意のあるユーザー）を投稿する可能性があります。-->
$('#comment_area').html("<%= escape_javascript(render 'book_comments/comment_index', book: @book) %>");