config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  
  resources :users, only: [:index, :show, :edit, :update] do
     resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings',as: 'followings'
    get 'followers' => 'relationships#followers',as: 'followers'
  end
  resources :books, only: [:index, :show, :edit, :create, :destroy, :update] do
      resource :favorites, only: [:create, :destroy]
      resources :book_comments, only: [:create, :destroy]
    end

  root 'homes#top'
  get '/home/about' => 'homes#about'
  get "search" => "search#search"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, uniqueness: true, length: { minimum: 2, maximum: 20}
  validates :introduction, length: { maximum: 50}
  
  has_many :books,dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォローしている人取得(Userのfollowerから見た関係)
  has_many :followed, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy # フォローされている人取得(Userのfolowedから見た関係)
  has_many :followings, through: :follower, source: :followed # 自分がフォローしている人
  has_many :followers, through: :followed, source: :follower  # 自分をフォローしている人(自分がフォローされている人)
  
  attachment :profile_image
  # ユーザーをフォローする
  def follow(user_id)
     follower.create(followed_id: user_id)
  end
  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end
  # フォロー確認をおこなう
  def following?(user)
    followings.include?(user)
  end

  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
     @user = User.find(params[:id])
     @book = Book.new
     @books = Book.where(user_id: @user.id)
  end

  def index
    @user = current_user
    @users = User.all
    @book = Book.new
    @books = Book.all
  end  

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user)
    end
  end

  def update
    if @user.update(user_params)
      redirect_to users_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<table class='table'>
  <tr><%= attachment_image_tag @user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
 
</table>

<div class="row">
	<%= render 'relationships/follow_button', user: user %>
</div>

app/views/users/_list.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="4"></th>

    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg" %></td>
        <td><%= user.name %></td>
        <td><p>フォロー数 : <%= link_to user.followings.count, user_followings_path(user) %></p></td>
        <td><p>フォロワー数 : <%= link_to user.followers.count, user_followers_path(user) %></p></td>
        <td>
          
        <% unless current_user == user %>
           <% if current_user.following?(user) %>
             <%= link_to 'フォローを外す', user_relationships_path(user.id), method: :delete %>
            <% else %>
             <%= link_to 'フォローする', user_relationships_path(user.id), method: :POST %>
            <% end %>
            
            <% end %>
          </td>
           
            <td><%= link_to "Show", user, class: "user_#{user.id}" %></td>   
            
        </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_profile.html.erb
<% user = current_user if user.nil? %>
<table class="table">
 <tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>

  <tr>
   <th>name</th>
   <th><%= user.name %></th>
  </tr>

  <tr>
   <th>introduction</th>
   <th><%= user.introduction %></th>
  </tr>

   <tr>
    <th>follows</th>
    <th><%= link_to user.followings.count, user_followings_path(user) %></th>
   </tr>

   <tr>
	   <th>followers</th>
    <th><%= link_to user.followers.count, user_followers_path(user) %></th>
		 </tr>
	<tr>
	<tr>
	  <th colspan="2">
	   <% if current_user == user %>
	     <%= link_to edit_user_path(user),class:"btn btn-secondary" do %>
		 	   <i class="fas fa-user-cog"></i>
		 	 <% end %> 
		 	<% else %>
		 	  	<%= render 'relationships/follow_button', user: user %>
		 	 <% end %>
		  </th>
	 </tr>
</table>

 	

app/views/users/edit.html.erb
<%#= render 'layouts/errors' %>
<div class="container">
  <div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

  <h2>User info</h2>
    
  <%= form_with model:@user,local:true do |f| %>

  
  <div class="user-name">Name</div>
    <%= f.text_field :name %>
  <div class="user-edit-image">Image</div>
    <%= f.attachment_field :profile_image %>
  <div class="form-body">Introduction</div>
    <%= f.text_area :introduction %><br>
  <div class="upload">
    <%= f.submit " Update User" %>
  </div>

    <%= link_to "Show", @user, class: "user_#{@user.id}" %>
    <%= link_to "Back", users_path, class: "back" %>
 <% end %>

 </div>
  
</div>

</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
   <div class="col-md-3">
       
    <h2>User info</h2>
    <%= render 'users/profile' %>
    <h2>New book</h2>
    <%= render 'books/form',book: @book %>
    </div>
    
    <div class="col-md-8 offset-md-1">
    <%= render 'layouts/search'%>
    <h2>Users</h2>
    <%= render 'users/list',users: @users %>
    
    </div>

   </div>
 </div>

<% if @user.id == current_user.id %>
	
<% end %>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/profile', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
       <%= render 'layouts/search'%>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>